CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_str_oil_analy]
(
  [fec_production_day] [smalldatetime] NOT NULL,
  [id_vers_stream] [nvarchar] (4000) NOT NULL,
  [id_stream] [nvarchar] (4000) NOT NULL,
  [id_fcty_class_1] [nvarchar] (4000) NOT NULL,
  [id_col_point] [nvarchar] (4000) NOT NULL,
  [id_productionunit] [nvarchar] (4000) NOT NULL,
  [id_area] [nvarchar] (4000) NOT NULL,
  [id_operator_route] [nvarchar] (4000) NOT NULL,
  [id_product] [nvarchar] (4000) NOT NULL,
  [id_licence] [nvarchar] (4000) NOT NULL,
  [id_disposition_type] [nvarchar] (4000) NOT NULL,
  [fec_start_date] [smalldatetime],
  [fec_lab_date] [smalldatetime],
  [des_analysis_status] [nvarchar] (4000),
  [ind_analysis_no] [int],
  [ind_api] [float],
  [fec_valid_from_date] [smalldatetime],
  [ind_salinity] [float],
  [des_phase] [nvarchar] (4000),
  [ind_bs_w_frac] [float],
  [ind_bs_w_pct] [float],
  [ind_bsw_wt_frac] [float],
  [ind_bsw_wt_pct] [float],
  [ind_cnpl_api_api] [float],
  [ind_density_lbsperstb] [float],
  [ind_density_gperscm3] [float],
  [ind_density_tonnesperstb] [float],
  [ind_density_kgpersm3] [float],
  [ind_salt_ppmv] [float],
  [ind_salt_ppm] [float],
  [ind_salt_mgperl] [float],
  [ind_sulfur_wt_tonnes] [float],
  [ind_sulfur_wt_lbs] [float],
  [ind_sulfur_wt_kg] [float],
  [ind_vapour_sm3persm3] [float],
  [ind_vapour_scfperstb] [float],
  [ind_vapour_scfperbbls] [float],
  [ind_vapour_mscfperbbls] [float],
  [ind_vapour_kscfperstb] [float],
  [ind_water_frac_ppmv] [float],
  [ind_water_frac_ppm] [float],
  [fec_create_date] [smalldatetime],
  [fec_update_date] [smalldatetime]
)
WITH
(
	DISTRIBUTION = HASH(id_stream),
	CLUSTERED COLUMNSTORE INDEX
)
GO