CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_well_deferm]
(
  [fec_production_day] [smalldatetime] NOT NULL,
  [id_vers_well] [nvarchar] (4000) NOT NULL,
  [id_well] [nvarchar] (4000) NOT NULL,
  [id_commercial_entity] [nvarchar] (4000) NOT NULL,
  [id_facility_class_1] [nvarchar] (4000) NOT NULL,
  [id_well_hookup] [nvarchar] (4000) NOT NULL,
  [id_well_hole] [nvarchar] (4000) NOT NULL,
  [id_area] [nvarchar] (4000) NOT NULL,
  [id_productionunit] [nvarchar] (4000) NOT NULL,
  [id_geo_area] [nvarchar] (4000) NOT NULL,
  [id_field_cds] [nvarchar] (4000) NOT NULL,
  [id_field] [nvarchar] (4000) NOT NULL,
  [id_basin] [nvarchar] (4000) NOT NULL,
  [id_operator_route] [nvarchar] (4000) NOT NULL,
  [id_col_point] [nvarchar] (4000) NOT NULL,
  [id_licence] [nvarchar] (4000) NOT NULL,
  [fec_end_date] [smalldatetime],
  [des_type] [nvarchar] (4000),
  [fec_parent_start_date] [nvarchar] (4000),
  [id_parent_well] [nvarchar] (4000),
  [ind_parent_no] [int],
  [ind_event_no] [varchar] (8000) NOT NULL, 
  [des_event_reason] [nvarchar] (4000),
  [des_event_category] [nvarchar] (4000),
  [des_event_system] [nvarchar] (4000),
  [des_root_cause] [nvarchar] (4000),
  [des_scheduled] [nvarchar] (4000),
  [ind_cond_event_loss_stb] [float],
  [ind_cond_event_loss_sm3] [float],
  [ind_cond_loss_volume_stb] [float],
  [ind_cond_loss_volume_sm3] [float],
  [ind_gas_event_loss_mscf] [float],
  [ind_gas_event_loss_kscf] [float],
  [ind_gas_event_loss_sm3] [float],
  [ind_gas_loss_volume_mscf] [float],
  [ind_gas_loss_volume_kscf] [float],
  [ind_gas_loss_volume_sm3] [float],
  [ind_oil_event_loss_stb] [float],
  [ind_oil_event_loss_sm3] [float],
  [ind_oil_event_loss_bbl] [float],
  [ind_oil_event_loss_boe] [float],
  [ind_oil_loss_volume_stb] [float],
  [ind_oil_loss_volume_sm3] [float],
  [ind_oil_loss_volume_bbl] [float],
  [ind_oil_loss_volume_boe] [float],
  [fec_create_date] [smalldatetime],
  [fec_update_date] [smalldatetime]
)
WITH
(
	DISTRIBUTION = HASH(id_well),
	CLUSTERED COLUMNSTORE INDEX
)
GO
