CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_well_oil_an]
(
  [fec_production_day] [smalldatetime] NOT NULL,
  [id_vers_well] [nvarchar] (4000) NOT NULL,
  [id_well] [nvarchar] (4000) NOT NULL,
  [id_commercial_entity] [nvarchar] (4000) NOT NULL,
  [id_facility_class_1] [nvarchar] (4000) NOT NULL,
  [id_well_hookup] [nvarchar] (4000) NOT NULL,
  [id_well_hole] [nvarchar] (4000) NOT NULL,
  [id_area] [nvarchar] (4000) NOT NULL,
  [id_productionunit] [nvarchar] (4000) NOT NULL,
  [id_geo_area] [nvarchar] (4000) NOT NULL,
  [id_field_cds] [nvarchar] (4000) NOT NULL,
  [id_field] [nvarchar] (4000) NOT NULL,
  [id_basin] [nvarchar] (4000) NOT NULL,
  [id_operator_route] [nvarchar] (4000) NOT NULL,
  [id_col_point] [nvarchar] (4000) NOT NULL,
  [id_licence] [nvarchar] (4000) NOT NULL,
  [fec_start_date] [smalldatetime],
  [fec_lab_daytime] [smalldatetime],
  [fec_valid_from] [smalldatetime],
  [ind_analysis_no] [bigint],
  [des_analysis_status] [nvarchar] (4000) ,
  [des_color] [nvarchar] (4000) ,
  [des_phase] [nvarchar] (4000) ,
  [ind_api] [float],
  [ind_asphaltene_ppmv] [float],
  [ind_asphaltene_ppm] [float],
  [ind_bsw_wt_frac] [float],
  [ind_bsw_wt_pct] [float],
  [ind_density_lbsperstb] [float],
  [ind_density_gperscm3] [float],
  [ind_density_tonnesperstb] [float],
  [ind_density_kgpersm3] [float],
  [ind_flash_gas_factor_scfperstb] [float],
  [ind_free_water_frac] [float],
  [ind_free_water_pct] [float],
  [ind_gcv_mmbtuperkscf] [float],
  [ind_gcv_btuperscf] [float],
  [ind_gcv_mjpersm3] [float],
  [ind_mol_wt_gpermol] [float],
  [ind_pto_escu_f] [float],
  [ind_pto_escu_c] [float],
  [ind_salt_ppmv] [float],
  [ind_salt_ppm] [float],
  [ind_sand_rate_frac] [float],
  [ind_sand_rate_pct] [float],
  [ind_sp_grav_sg] [float],
  [ind_sulfate_ppmv] [float],
  [ind_sulfate_ppm] [float],
  [ind_wat_density_kgpersm3] [float],
  [ind_wat_density_gperscm3] [float],
  [ind_wat_density_lbsperstb] [float],
  [fec_create_date] [smalldatetime] ,
  [fec_update_date] [smalldatetime] 
)
WITH
(
	DISTRIBUTION = HASH(id_well),
	CLUSTERED COLUMNSTORE INDEX
)
GO