CREATE TABLE [sch_anl].[eyp0007_tb_fac_m_str_plan_budg]
(
  [fec_production_day] [smalldatetime] NOT NULL,
  [id_vers_stream] [nvarchar] (4000) NOT NULL,
  [id_stream] [nvarchar] (4000) NOT NULL,
  [id_fcty_class_1] [nvarchar] (4000) NOT NULL,
  [id_col_point] [nvarchar] (4000) NOT NULL,
  [id_productionunit] [nvarchar] (4000) NOT NULL,
  [id_area] [nvarchar] (4000) NOT NULL,
  [id_operator_route] [nvarchar] (4000) NOT NULL,
  [id_product] [nvarchar] (4000) NOT NULL,
  [id_licence] [nvarchar] (4000) NOT NULL,
  [id_disposition_type] [nvarchar] (4000) NOT NULL,
  [fec_start_date] [smalldatetime] NOT NULL,
  [des_comments] [nvarchar] (4000),
  [ind_cond_rate_kstbpermth] [float],
  [ind_cond_rate_stbpermth] [float],
  [ind_cond_rate_net_kstbpermth] [float],
  [ind_cond_rate_net_stbpermth] [float],
  [ind_cond_rate_wi_kstbpermth] [float],
  [ind_cond_rate_wi_stbpermth] [float],
  [ind_gas_rate_mmscfpermth] [float],
  [ind_gas_rate_kscfpermth] [float],
  [ind_gas_rate_net_mmscfpermth] [float],
  [ind_gas_rate_net_kscfpermth] [float],
  [ind_gas_rate_wi_mmscfpermth] [float],
  [ind_gas_rate_wi_kscfpermth] [float],
  [ind_ngl_rate_mscfperday] [float],
  [ind_ngl_rate_kscfperday] [float],
  [ind_ngl_rate_sm3perday] [float],
  [ind_ngl_rate_kstbpermth] [float],
  [ind_ngl_rate_stbpermth] [float],
  [ind_ngl_rate_net_kstbpermth] [float],
  [ind_ngl_rate_net_stbpermth] [float],
  [ind_ngl_rate_net_mmscfpermth] [float],
  [ind_ngl_rate_net_kscfpermth] [float],
  [ind_ngl_rate_wi_kstbpermth] [float],
  [ind_ngl_rate_wi_stbpermth] [float],
  [ind_ngl_rate_wi_mmscfpermth] [float],
  [ind_ngl_rate_wi_kscfpermth] [float],
  [ind_oil_rate_kstbpermth] [float],
  [ind_oil_rate_stbpermth] [float],
  [ind_oil_rate_net_kstbpermth] [float],
  [ind_oil_rate_net_stbpermth] [float],
  [ind_oil_rate_wi_kstbpermth] [float],
  [ind_oil_rate_wi_stbpermth] [float],
  [fec_create_date] [smalldatetime],
  [fec_update_date] [smalldatetime]
)
WITH
(
	DISTRIBUTION = HASH(id_stream),
	CLUSTERED COLUMNSTORE INDEX
)
GO