CREATE TABLE [sch_anl].[eyp0007_tb_dim_d_wellbore_un]
( 
  [fec_start_date_rel] [datetime2] NOT NULL,
  [fec_end_date_rel] [datetime2],
  [id_vers_rel] [nvarchar] (4000) NOT NULL,
  [id_vers]	[nvarchar] (4000) NOT NULL,
  [id_well_bore] [nvarchar] (4000)  NOT NULL,
  [des_well_bore] [nvarchar] (4000) ,
  [cod_uwbi] [nvarchar] (4000),
  [cod_uwi] [nvarchar] (4000),
  [cod_api12] [nvarchar] (4000),
  [des_wellbore_cds] [nvarchar] (4000),
  [fec_start_date] [smalldatetime] NOT NULL,
  [fec_end_date] [smalldatetime],
  [id_vers_well] [nvarchar] (4000) NOT NULL,
  [id_vers_well_hole] [nvarchar] (4000) NOT NULL,
  [id_well] [nvarchar] (4000) ,
  [des_country] [nvarchar] (4000) ,
  [ind_east_utm_td] [float] ,
  [ind_north_utm_td] [float] ,
  [ind_rkb_depth] [float] ,
  [ind_sidetrack_depth] [float] ,
  [ind_tvdss_depth] [float] ,
  [ind_borehole_number] [int],
  [des_common_name] [nvarchar] (4000),
  [des_current_purpose] [nvarchar] (4000),
  [fec_completed_date] [datetime2],
  [des_depth_ref_datum] [nvarchar] (4000),
  [ind_depth_ref_elev] [float],
  [des_depth_ref_elev_unit] [nvarchar] (4000),
  [des_depth_ref_point] [nvarchar] (4000),
  [des_drilling_operator] [nvarchar] (4000),
  [des_drilling_permit] [nvarchar] (4000),
  [id_field] [nvarchar] (4000),
  [des_field] [nvarchar] (4000),
  [ind_ground_elev] [float],
  [des_ground_elev_unit] [nvarchar] (4000),
  [des_innitial_purpose] [nvarchar] (4000),
  [ind_kickoff_depth] [float],
  [des_kickoff_depth_unit] [nvarchar] (4000),
  [des_kind] [nvarchar] (4000),
  [des_norm_bh_geo_coord_sys] [nvarchar] (4000),
  [ind_normalized_bh_latitude] [float],
  [ind_normalized_bh_longitude] [float],
  [des_original_operator] [nvarchar] (4000),
  [id_cds_parent] [nvarchar] (4000),
  [des_pref_bh_geo_coord_sys] [nvarchar] (4000),
  [ind_preferred_bh_latitude] [float] ,
  [ind_preferred_bh_longitude] [float] ,
  [des_pref_bh_prj_coord_sys] [nvarchar] (4000),
  [des_pref_bh_prj_coord_unit] [nvarchar] (4000),
  [ind_preffered_bh_easting] [float] ,
  [ind_preffered_bh_northing] [float] ,
  [fec_wellbore_spud_date] [datetime2], 
  [ind_total_depth_final] [float],
  [des_total_depth_final_unit] [nvarchar] (4000),
  [ind_total_depth_planned] [float],
  [des_total_depth_planned_unit] [nvarchar] (4000),
  [des_trajectory_shape] [nvarchar] (4000),
  [val_geo_offset_east_bh] [float],
  [val_geo_offset_north_bh] [float],
  [val_geo_latitude_bh] [float],
  [val_geo_longitude_bh] [float],
  [fec_date_td_reached] [datetime2],
  [val_bh_md] [float],
  [val_bh_tvd] [float],
  [val_mid_lateral_x] [float],
  [val_mid_lateral_y] [float],
  [val_mid_lateral_md] [float],
  [val_mid_lateral_tvd] [float],
  [des_casing_p_phase] [nvarchar] (4000),
  [val_casing_p_hole_size] [float],
  [val_casing_p_diameter] [float],
  [val_casing_p_shoe_depth] [float],
  [des_casing_1_phase] [nvarchar] (4000),
  [val_casing_1_hole_size] [float],
  [val_casing_1_diameter] [float],
  [val_casing_1_shoe_depth] [float],
  [des_casing_2_phase] [nvarchar] (4000),
  [val_casing_2_hole_size] [float],
  [val_casing_2_diameter] [float],
  [val_casing_2_shoe_depth] [float],
  [des_casing_3_phase] [nvarchar] (4000),
  [val_casing_3_hole_size] [float],
  [val_casing_3_diameter] [float],
  [val_casing_3_shoe_depth] [float],
  [bol_flag_tubing] [int], 
  [val_latitude] [float],
  [val_longitude] [float],
  [fec_create_date] [datetime2],
  [fec_update_date] [datetime2],
  [des_business_unit] [nvarchar] (4000),
  [val_landing_md] [float],
  [val_landing_tvd] [float],
  [val_landing_x] [float],
  [val_landing_y] [float],
  [val_landing_latitude] [float],
  [val_landing_longitude] [float],
  [val_proportion_non_nulls] [float]
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX (id_vers)
)
GO