CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_enverus]
(
  [cod_vers_wellbore] [nvarchar] (4000) NOT NULL,
  [cod_uwbi] [nvarchar] (4000),
  [cod_api12] [nvarchar] (4000),
  [des_API_UWI] [nvarchar] (4000),
  [des_Unformatted_API_UWI] [nvarchar] (4000),
  [des_API_UWI_12] [nvarchar] (4000),
  [des_Unformatted_API_UWI_12] [nvarchar] (4000),
  [des_API_UWI_14] [nvarchar] (4000),
  [des_Unformatted_API_UWI_14] [nvarchar] (4000),
  [num_CompletionID] [int],
  [des_WellPadID] [nvarchar] (4000),
  [des_WellPadDirection] [nvarchar] (4000),
  [des_WellName] [nvarchar] (4000),
  [des_Country] [nvarchar] (4000),
  [des_StateProvince] [nvarchar] (4000),
  [des_County] [nvarchar] (4000),
  [des_LeaseName] [nvarchar] (4000),
  [des_ENVOperator] [nvarchar] (4000),
  [des_ENVTicker] [nvarchar] (4000),
  [des_ENVBasin] [nvarchar] (4000),
  [des_ENVPlay] [nvarchar] (4000),
  [des_ENVInterval] [nvarchar] (4000),
  [val_ENVSpacingAssumption] [float],
  [des_ENVWellStatus] [nvarchar] (4000),
  [des_Trajectory] [nvarchar] (4000),
  [des_Formation] [nvarchar] (4000),
  [des_FirstProdDate] [nvarchar] (4000),
  [val_Latitude] [float],
  [val_Longitude] [float],
  [val_Latitude_BH] [float],
  [val_Longitude_BH] [float],
  [val_TVD_FT] [float],
  [val_MD_FT] [float],
  [des_WellNumber] [nvarchar] (4000),
  [val_Vintage] [float],
  [val_ElevationGL_FT] [float],
  [des_SpudDate] [nvarchar] (4000),
  [des_CompletionDate] [nvarchar] (4000),
  [val_UpperPerf_FT] [float],
  [val_LowerPerf_FT] [float],
  [val_LateralLength_FT] [float],
  [val_FracStages] [float],
  [val_ProppantIntensity_LBSPerFT] [float],
  [val_FluidIntensity_BBLPerFT] [float],
  [val_First3MonthProd_BOE] [float],
  [val_First3MonthProd_BOEPer1000FT] [float],
  [val_First3MonthGas_MCF] [float],
  [val_First3MonthGas_MCFPer1000FT] [float],
  [val_First3MonthOil_BBL] [float],
  [val_First3MonthOil_BBLPer1000FT] [float],
  [val_First3MonthWater_BBL] [float],
  [val_First6MonthProd_BOE] [float],
  [val_First6MonthProd_BOEPer1000FT] [float],
  [val_First6MonthGas_MCF] [float],
  [val_First6MonthGas_MCFPer1000FT] [float],
  [val_First6MonthOil_BBL] [float],
  [val_First6MonthOil_BBLPer1000FT] [float],
  [val_First6MonthWater_BBL] [float],
  [val_First9MonthProd_BOE] [float],
  [val_First9MonthProd_BOEPer1000FT] [float],
  [val_First9MonthGas_MCF] [float],
  [val_First9MonthGas_MCFPer1000FT] [float],
  [val_First9MonthOil_BBL] [float],
  [val_First9MonthOil_BBLPer1000FT] [float],
  [val_First9MonthWater_BBL] [float],
  [val_First12MonthProd_BOE] [float],
  [val_First12MonthProd_BOEPer1000FT] [float],
  [val_First12MonthGas_MCF] [float],
  [val_First12MonthGas_MCFPer1000FT] [float],
  [val_First12MonthOil_BBL] [float],
  [val_First12MonthOil_BBLPer1000FT] [float],
  [val_First12MonthWater_BBL] [float],
  [val_First36MonthProd_BOE] [float],
  [val_First36MonthProd_BOEPer1000FT] [float],
  [val_First36MonthGas_MCF] [float],
  [val_First36MonthGas_MCFPer1000FT] [float],
  [val_First36MonthOil_BBL] [float],
  [val_First36MonthOil_BBLPer1000FT] [float],
  [val_First36MonthWater_BBL] [float],
  [des_PeakProductionDate] [nvarchar] (4000),
  [val_MonthsToPeakProduction] [float],
  [val_PeakProd_BOE] [float],
  [val_PeakProd_BOEPer1000FT] [float],
  [val_PeakGas_MCF] [float],
  [val_PeakGas_MCFPer1000FT] [float],
  [val_PeakOil_BBL] [float],
  [val_PeakOil_BBLPer1000FT] [float],
  [val_PeakWater_BBL] [float],
  [val_TotalProducingMonths] [float],
  [val_GOR_ScfPerBbl] [float],
  [val_ToeAngle_DEG] [float],
  [des_ParentChildAnyZone] [nvarchar] (4000),
  [des_ParentChildSameZone] [nvarchar] (4000),
  [des_BoundedAnyZone] [nvarchar] (4000),
  [des_BoundedSameZone] [nvarchar] (4000),
  [val_DrillingCost_USDMM] [float],
  [val_CompletionCost_USDMM] [float],
  [val_TieInCost_USDMM] [float],
  [val_TotalWellCost_USDMM] [float],
  [val_EURWH_MBOE] [float],
  [val_OilEURWH_MBBL] [float],
  [val_GasEURWH_BCF] [float],
  [val_GasInitialRate] [float],
  [val_GasBFactor] [float],
  [val_GasInitialDecline] [float],
  [val_GasTerminalDecline] [float],
  [val_OilInitialRate] [float],
  [val_OilBFactor] [float],
  [val_OilInitialDecline] [float],
  [val_OilTerminalDecline] [float],
  [des_ENVSpacingClass_AnyZone] [nvarchar] (4000),
  [des_ENVSpacingClass_SameZone] [nvarchar] (4000),
  [des_ENVSpacingClass_Within100] [nvarchar] (4000),
  [des_ENVSpacingClass_AnyZoneAtInitialClass] [nvarchar] (4000),
  [des_ENVSpacingClass_SameZoneAtInitialClass] [nvarchar] (4000),
  [des_ENVSpacingClass_Vertical100AtInitialClass] [nvarchar] (4000),
  [val_EURWH_MBOEPer1000FT] [float],
  [val_OilEURWH_MBBLPer1000FT] [float],
  [val_GasEURWH_BCFPer1000FT] [float]
)
WITH
(
  DISTRIBUTION = HASH(cod_vers_wellbore),
  CLUSTERED COLUMNSTORE INDEX
)
GO


