CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_dd_zv_mur]
(
  [fec_production_day] [smalldatetime] NOT NULL,
  [id_licence] [nvarchar] (4000) NOT NULL,
  [id_mur] [nvarchar] (4000),
  [des_reserves_area] [nvarchar] (4000) ,
  [des_reservoir] [nvarchar] (4000) ,
  [ind_of_grs_condensate_bbl] [float] ,
  [ind_of_grs_gas_boe] [float] ,
  [ind_of_grs_gas_dissolved_boe] [float] ,
  [ind_of_grs_gas_dissolved_mscf] [float] ,
  [ind_of_grs_gas_mscf] [float] ,
  [ind_of_grs_ngl_bbl] [float] ,
  [ind_of_grs_oil_primary_bbl] [float] ,
  [ind_of_net_gas_boe] [float] ,
  [ind_of_net_gas_dissolved_boe] [float] ,
  [ind_of_net_condensate_bbl] [float] ,
  [ind_of_net_gas_dissolved_mscf] [float] ,
  [ind_of_net_gas_mscf] [float] ,
  [ind_of_net_ngl_bbl] [float] ,
  [ind_of_net_oil_primary_bbl] [float] ,
  [ind_of_wi_condensate_bbl] [float] ,
  [ind_of_wi_gas_boe] [float] ,
  [ind_of_wi_gas_dissolved_boe] [float] ,
  [ind_of_wi_gas_dissolved_mscf] [float] ,
  [ind_of_wi_gas_mscf] [float] ,
  [ind_of_wi_ngl_bbl] [float] ,
  [ind_of_wi_oil_primary_bbl] [float] ,
  [ind_prov_grs_condensate_bbl] [float] ,
  [ind_prov_grs_gas_boe] [float] ,
  [ind_prov_grs_gas_dissolved_boe] [float] ,
  [ind_prov_grs_gas_dissolve_mscf] [float] ,
  [ind_prov_grs_gas_mscf] [float] ,
  [ind_prov_grs_ngl_bbl] [float] ,
  [ind_prov_grs_oil_primary_bbl] [float] ,
  [ind_prov_net_condensate_bbl] [float] ,
  [ind_prov_net_gas_boe] [float] ,
  [ind_prov_net_gas_dissolved_boe] [float] ,
  [ind_prov_net_gas_dissolve_mscf] [float] ,
  [ind_prov_wi_gas_dissolved_boe] [float] ,
  [ind_prov_wi_gas_dissolved_mscf] [float] ,
  [ind_prov_net_gas_mscf] [float] ,
  [ind_prov_net_ngl_bbl] [float] ,
  [ind_prov_net_oil_primary_bbl] [float] ,
  [ind_prov_wi_condensate_bbl] [float] ,
  [ind_prov_wi_gas_boe] [float] ,
  [ind_prov_wi_gas_mscf] [float] ,
  [ind_prov_wi_ngl_bbl] [float] ,
  [ind_prov_wi_oil_primary_bbl] [float],
  [id_area] [nvarchar] (4000),
  [id_facility_class_1] [nvarchar] (4000),
  [id_productionunit] [nvarchar] (4000),
  [cod_object] [nvarchar] (4000),
  [cod_vers_object] [nvarchar] (4000)
)
WITH
(
	DISTRIBUTION = HASH(id_mur),
	CLUSTERED COLUMNSTORE INDEX
)
GO