CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_field_header]
(
  [cod_field]                   NVARCHAR(4000)   NOT NULL,
  [des_field]                   NVARCHAR(4000)   NULL,
  [des_country]                 NVARCHAR(4000)   NULL,
  [des_state_province]          NVARCHAR(4000)   NULL,
  [des_field_type]              NVARCHAR(4000)   NULL,
  [cod_field_code]              NVARCHAR(4000)   NULL,
  [num_field_number]            INT              NULL,
  [des_primary_reservoir]       NVARCHAR(4000)   NULL,
  [cod_owner]                   NVARCHAR(4000)   NULL,
  [des_curr_operator]           NVARCHAR(4000)   NULL,
  [des_curr_status]             NVARCHAR(4000)   NULL,
  [des_producing_status]        NVARCHAR(4000)   NULL,
  [cod_parent]                  NVARCHAR(4000)   NULL,
  [des_parent_name]             NVARCHAR(4000)   NULL,
  [des_parent_type]             NVARCHAR(4000)   NULL,
  [des_nearest_discovery]       NVARCHAR(4000)   NULL,
  [des_supply_base]             NVARCHAR(4000)   NULL,
  [ind_multi_reservoir]         NVARCHAR(4000)   NULL,
  [des_prospect]                NVARCHAR(4000)   NULL,
  [fec_drill_start]             DATETIME         NULL,
  [fec_drill_end]               DATETIME         NULL,
  [cod_notion_wb]               NVARCHAR(4000)   NULL,
  [cod_notion_w]                NVARCHAR(4000)   NULL,
  [des_notion_wb]               NVARCHAR(4000)   NULL,
  [des_fluid_type]              NVARCHAR(4000)   NULL,
  [des_disc_basis]              NVARCHAR(4000)   NULL,
  [cod_disc_wb]                 NVARCHAR(4000)   NULL,
  [cod_disc_w]                  NVARCHAR(4000)   NULL,
  [des_disc_wb]                 NVARCHAR(4000)   NULL,
  [fec_discovery]               DATETIME         NULL,
  [des_onshore_offshore]        NVARCHAR(4000)   NULL,
  [fec_first_prod]              DATETIME         NULL,
  [fec_last_prod]               DATETIME         NULL,
  [cod_basin]                   NVARCHAR(4000)   NULL,
  [des_basin]                   NVARCHAR(4000)   NULL,
  [des_basin_abbr]              NVARCHAR(4000)   NULL,
  [des_basin_type]              NVARCHAR(4000)   NULL,
  [des_play]                    NVARCHAR(4000)   NULL,
  [des_trend]                   NVARCHAR(4000)   NULL,
  [val_drill_prob]              FLOAT            NULL,
  [val_latitude]                FLOAT            NULL,
  [val_longitude]               FLOAT            NULL,
  [des_geo_coord_sys]           NVARCHAR(4000)   NULL,
  [val_easting]                 FLOAT            NULL,
  [val_northing]                FLOAT            NULL,
  [des_coord_unit]              NVARCHAR(4000)   NULL,
  [des_coord_sys]               NVARCHAR(4000)   NULL,
  [val_dist_shore]              FLOAT            NULL,
  [des_dist_unit]               NVARCHAR(4000)   NULL,
  [val_pipe_dist]               FLOAT            NULL,
  [val_facility_dist]           FLOAT            NULL,
  [val_water_depth]             FLOAT            NULL,
  [des_water_depth_unit]        NVARCHAR(4000)   NULL,
  [val_est_dev_cost]            FLOAT            NULL,
  [val_act_dev_cost]            FLOAT            NULL,
  [des_currency]                NVARCHAR(4000)   NULL,
  [fec_create]                  DATETIME         NULL,
  [cod_create_user]             NVARCHAR(4000)   NULL,
  [fec_update]                  DATETIME         NULL,
  [cod_update_user]             NVARCHAR(4000)   NULL
)
WITH
(
  DISTRIBUTION = HASH(cod_field),
  CLUSTERED COLUMNSTORE INDEX
)
GO
