CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_well_plan_oth]
(
  [fec_production_day] [smalldatetime] NOT NULL,
  [id_vers_well] [nvarchar] (4000) NOT NULL,
  [id_well] [nvarchar] (4000) NOT NULL,
  [id_commercial_entity] [nvarchar] (4000) NOT NULL,
  [id_facility_class_1] [nvarchar] (4000) NOT NULL,
  [id_well_hookup] [nvarchar] (4000) NOT NULL,
  [id_well_hole] [nvarchar] (4000) NOT NULL,
  [id_area] [nvarchar] (4000) NOT NULL,
  [id_productionunit] [nvarchar] (4000) NOT NULL,
  [id_geo_area] [nvarchar] (4000) NOT NULL,
  [id_field_cds] [nvarchar] (4000) NOT NULL,
  [id_field] [nvarchar] (4000) NOT NULL,
  [id_basin] [nvarchar] (4000) NOT NULL,
  [id_operator_route] [nvarchar] (4000) NOT NULL,
  [id_col_point] [nvarchar] (4000) NOT NULL,
  [id_licence] [nvarchar] (4000) NOT NULL,
  [fec_start_date] [smalldatetime],
  [des_comments] [nvarchar] (4000),
  [ind_aof_cond_rate_stbperday] [float],
  [ind_aof_cond_rate_sm3perday] [float],
  [ind_aof_gas_rate_mscfperday] [float],
  [ind_aof_gas_rate_kscfperday] [float],
  [ind_aof_gas_rate_sm3perday] [float],
  [ind_aof_oil_rate_stbperday] [float],
  [ind_aof_oil_rate_sm3perday] [float],
  [ind_aof_wat_inj_rate_stbperday] [float],
  [ind_aof_wat_inj_rate_sm3perday] [float],
  [ind_aof_water_rate_stbperday] [float],
  [ind_aof_water_rate_sm3perday] [float],
  [ind_cond_rate_stbperday] [float],
  [ind_cond_rate_sm3perday] [float],
  [ind_gas_inj_rate_mscfperday] [float],
  [ind_gas_inj_rate_kscfperday] [float],
  [ind_gas_inj_rate_sm3perday] [float],
  [ind_gas_rate_mscfperday] [float],
  [ind_gas_rate_kscfperday] [float],
  [ind_gas_rate_sm3perday] [float],
  [ind_oil_rate_stbperday] [float],
  [ind_oil_rate_sm3perday] [float],
  [ind_wat_inj_rate_stbperday] [float],
  [ind_wat_inj_rate_sm3perday] [float],
  [ind_water_rate_stbperday] [float],
  [ind_water_rate_sm3perday] [float],
  [fec_create_date] [smalldatetime] ,
  [fec_update_date] [smalldatetime] 
)
WITH
(
	DISTRIBUTION = HASH(id_well),
	CLUSTERED COLUMNSTORE INDEX
)
GO