CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_geosteering]
(
  [cod_vers_wellbore] [nvarchar] (100) NOT NULL,
  [cod_vers_well_string] [nvarchar] (4000) NOT NULL,
  [cod_vers_well] [nvarchar] (4000) NOT NULL,
  [cod_uwbi] [nvarchar] (100) NULL,
  [cod_api12] [nvarchar] (100) NULL,
  [val_md] [float] NULL,
  [val_z] [float] NULL,
  [val_azimuth] [float] NULL,
  [val_inclination] [float] NULL,
  [val_vs_azim_azimuth] [float] NULL,
  [val_vs_azim_vs] [float] NULL,
  [des_hor_ac_0] [float] NULL,
  [des_hor_ac_10] [float] NULL,
  [des_hor_ac_20] [float] NULL,
  [des_hor_anacacho] [float] NULL,
  [des_hor_austinchalk] [float] NULL,
  [des_hor_basemodel] [float] NULL,
  [des_hor_blue] [float] NULL,
  [des_hor_brallier] [float] NULL,
  [des_hor_brown] [float] NULL,
  [des_hor_buda] [float] NULL,
  [des_hor_cherry_valley] [float] NULL,
  [des_hor_cookmountain] [float] NULL,
  [des_hor_delrio] [float] NULL,
  [des_hor_eaglefordlower] [float] NULL,
  [des_hor_eaglefordmiddle] [float] NULL,
  [des_hor_eaglefordupper] [float] NULL,
  [des_hor_edwards] [float] NULL,
  [des_hor_escondido] [float] NULL,
  [des_hor_geneseo] [float] NULL,
  [des_hor_georgetown] [float] NULL,
  [des_hor_green] [float] NULL,
  [des_hor_lef_mfs] [float] NULL,
  [des_hor_lef_sb0] [float] NULL,
  [des_hor_lef_sb1] [float] NULL,
  [des_hor_lef_sb2] [float] NULL,
  [des_hor_lef_sb3] [float] NULL,
  [des_hor_lock_haven] [float] NULL,
  [des_hor_lower_tz_base] [float] NULL,
  [des_hor_lower_tz_top] [float] NULL,
  [des_hor_maness] [float] NULL,
  [des_hor_midway] [float] NULL,
  [des_hor_moscow] [float] NULL,
  [des_hor_moscow_dm_a] [float] NULL,
  [des_hor_moscow_dm_b] [float] NULL,
  [des_hor_moscow_dm_c] [float] NULL,
  [des_hor_navarro] [float] NULL,
  [des_hor_no_go] [float] NULL,
  [des_hor_no_go_efd] [float] NULL,
  [des_hor_olmos] [float] NULL,
  [des_hor_onondaga] [float] NULL,
  [des_hor_orange] [float] NULL,
  [des_hor_queen_city] [float] NULL,
  [des_hor_red] [float] NULL,
  [des_hor_reklaw] [float] NULL,
  [des_hor_sanmiguel] [float] NULL,
  [des_hor_sparta] [float] NULL,
  [des_hor_taylor] [float] NULL,
  [des_hor_tully] [float] NULL,
  [des_hor_union_springs] [float] NULL,
  [des_hor_upper_marcellus] [float] NULL,
  [des_hor_upson] [float] NULL,
  [des_hor_weches] [float] NULL,
  [des_hor_wilcoxlower] [float] NULL,
  [des_hor_wilcoxmiddle] [float] NULL,
  [des_hor_wilcoxupper] [float] NULL,
  [des_hor_yegua] [float] NULL,
  [des_hor_marker] [float] NULL,
  [des_hor_pearsall] [float] NULL,
  [des_hor_sligo] [float] NULL,
  [des_hor_vicksburg] [float] NULL,
  [des_geosteering_log] [nvarchar] (100) NULL,
  [bol_flag_cambio] [int] NOT NULL,
  [cod_api] [nvarchar] (100) NULL,
  [val_geosteering_x_coord] [float] NULL,
  [val_geosteering_y_coord] [float] NULL,
  [val_geosteering_latitude] [float] NULL,
  [val_geosteering_longitude] [float] NULL

)
WITH 
(
    DISTRIBUTION = HASH([cod_api]),
    CLUSTERED COLUMNSTORE INDEX
);
