CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_isip]
(
  [cod_vers_wellbore] [nvarchar] (4000) NOT NULL,
  [cod_vers_well_string] [nvarchar] (4000) NOT NULL,
  [cod_vers_well] [nvarchar] (4000) NOT NULL,
  [cod_vers] [nvarchar] (4000),
  [cod_uwbi] [varchar] (26),
  [cod_uwbi_num_stage] [varchar] (4000),
  [fec_start_date] [datetime],
  [num_stage] [int] NOT NULL,
  [val_wellhead_pressure] [float],
  [val_slurry_flow_rate] [float],
  [val_elapsed_time] [float],
  [val_clean_flow_rate] [float],
  [val_tot_clean_vol] [float],
  [val_tot_slurry_vol] [float],
  [val_tot_chem_rate] [float],
  [val_tot_fric_reduc] [float],
  [val_tot_propp_conc] [float],
  [val_tot_propp_mass] [float],
  [val_bottomhole_propp_conc] [float],
  [val_hydrostatic_press] [float],
  [val_inverse_hydrostatic_press] [float],
  [val_enzyme_breaker] [float],
  [val_scale_inhibitor] [float],
  [val_surfactant] [float],
  [val_friction_reducer] [float],
  [val_friction_reducer_extra] [float],
  [val_cross_linker] [float],
  [val_acid] [float],
  [val_gel] [float],
  [val_ph_adjusting_agent] [float],
  [val_accelerator] [float],
  [val_fluid_loss] [float],
  [val_ploymer_plug] [float],
  [val_acid_inhibitor] [float],
  [val_acid_retarder] [float],
  [val_emulsifier] [float],
  [val_clay_stabilizer] [float],
  [val_non_emulsifier] [float],
  [val_fines_suspender] [float],
  [val_anti_sludge] [float],
  [val_iron_control] [float],
  [val_oxygen_scavenger] [float],
  [val_mutual_solvent] [float],
  [val_corrosion_inhibitor] [float],
  [val_paraffin_control] [float],
  [val_biocide] [float],
  [val_instant_crosslinker] [float],
  [val_delayed_crosslinker] [float],
  [val_liquid_breaker] [float],
  [val_powder_breaker] [float],
  [val_divertor] [float],
  [val_powder_gel] [float],
  [val_powder_friction_reducer] [float],
  [val_powder_enzyme_breaker] [float],
  [val_propp1_conc] [float],
  [val_propp2_conc] [float],
  [val_backside_press] [float],
  [val_is_valid] [bit]
)
WITH
(
  DISTRIBUTION = HASH(cod_vers),
  CLUSTERED COLUMNSTORE INDEX
)
GO
