CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_tpl_bo_wl_def]
(
  [fec_production_day] [smalldatetime] NOT NULL,
  [id_vers_well] [nvarchar] (4000) NOT NULL,
  [id_well] [nvarchar] (4000) NOT NULL,
  [id_commercial_entity] [nvarchar] (4000) NOT NULL,
  [id_facility_class_1] [nvarchar] (4000) NOT NULL,
  [id_well_hookup] [nvarchar] (4000) NOT NULL,
  [id_well_hole] [nvarchar] (4000) NOT NULL,
  [id_area] [nvarchar] (4000) NOT NULL,
  [id_productionunit] [nvarchar] (4000) NOT NULL,
  [id_geo_area] [nvarchar] (4000) NOT NULL,
  [id_field_cds] [nvarchar] (4000) NOT NULL,
  [id_field] [nvarchar] (4000) NOT NULL,
  [id_basin] [nvarchar] (4000) NOT NULL,
  [id_operator_route] [nvarchar] (4000) NOT NULL,
  [id_col_point] [nvarchar] (4000) NOT NULL,
  [id_licence] [nvarchar] (4000) NOT NULL,
  [fec_start_production_date] [smalldatetime],
  [fec_end_production_date] [smalldatetime],
  [fec_end_production_day] [smalldatetime],
  [des_comments] [nvarchar] (4000),
  [id_event_no] [varchar] (8000) NOT NULL,
  [id_sap_pm_notif] [bigint],
  [id_scheduled] [nvarchar] (4000),
  [ind_hrs_total] [float],
  [des_event_category_code] [nvarchar] (4000),
  [des_event_reason_code] [nvarchar] (4000),
  [des_event_system_code] [nvarchar] (4000),
  [ind_hours] [float],
  [des_object_type] [nvarchar] (4000),
  [des_root_cause] [nvarchar] (4000),
  [ind_cond_event_loss_sm3] [float],
  [ind_cond_event_loss_stb] [float],
  [ind_gas_event_loss_kscf] [float],
  [ind_oil_event_loss_sm3] [float],
  [ind_oil_event_loss_stb] [float],
  [fec_create_date] [smalldatetime],
  [fec_update_date] [smalldatetime],
  [cod_commentity_ec_id] [nvarchar] (4000),
  [cod_fcty_ec_id] [nvarchar] (4000),
  [cod_whook_ec_id] [nvarchar] (4000),
  [cod_wellhole_ec_id] [nvarchar] (4000),
  [cod_produnit_ec_id] [nvarchar] (4000),
  [cod_geoarea_ec_id] [nvarchar] (4000),
  [cod_field_cds_id] [nvarchar] (4000),
  [cod_field_ec_id] [nvarchar] (4000),
  [cod_basin_cds_id] [nvarchar] (4000),
  [cod_oprout_ec_id] [nvarchar] (4000),
  [cod_colpoint_ec_id] [nvarchar] (4000),
  [cod_licence_ec_id] [nvarchar] (4000)
)
WITH
(
	DISTRIBUTION = HASH(id_well),
	CLUSTERED COLUMNSTORE INDEX
)
GO