CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_well_summary]
(
    [cod_vers_wellbore] [nvarchar] (100) NOT NULL,
    [des_well_hole] [nvarchar] (100),
    [cod_uwi] [nvarchar] (100),
    [cod_uwbi] [nvarchar] (100),
    [cod_api10] [nvarchar] (100),
    [cod_api12] [nvarchar] (100),
    [des_county] [nvarchar] (100),
    [des_installation_name] [nvarchar] (100),
    [fec_spud_date] [datetime2],
    [fec_completion_date] [datetime2],
    [num_stages] [bigint],
    [val_completed_length] [float],
    [val_stage_length] [float],
    [avg_length_stages] [float],
    [val_sand_loading] [float],
    [val_fluid_loading] [float],
    [fec_first_prod_day] [datetime2],
    [num_days_producing] [int],
    [fec_max_cond_vol] [datetime2],
    [val_max_cond_vol_stb] [float],
    [fec_max_gas_vol] [datetime2],
    [val_max_gas_vol_mscf] [float],
    [fec_max_oil_vol] [datetime2],
    [val_max_oil_vol_stb] [float],
    [fec_max_water_vol] [datetime2],
    [val_max_water_vol_bbl] [float],
    [avg_cond_gas_rt_15days] [float],
    [val_acum_cond_vol_1_m_stb] [float],
    [val_acum_cond_vol_3_m_stb] [float],
    [val_acum_cond_vol_6_m_stb] [float],
    [val_acum_cond_vol_12_m_stb] [float],
    [val_acum_cond_vol_18_m_stb] [float],
    [val_acum_cond_vol_24_m_stb] [float],
    [val_acum_cond_vol_tot_stb] [float],
    [val_acum_gas_vol_1_m_mscf] [float],
    [val_acum_gas_vol_3_m_mscf] [float],
    [val_acum_gas_vol_6_m_mscf] [float],
    [val_acum_gas_vol_12_m_mscf] [float],
    [val_acum_gas_vol_18_m_mscf] [float],
    [val_acum_gas_vol_24_m_mscf] [float],
    [val_acum_gas_vol_tot_mscf] [float],
    [val_acum_oil_vol_1_m_stb] [float],
    [val_acum_oil_vol_3_m_stb] [float],
    [val_acum_oil_vol_6_m_stb] [float],
    [val_acum_oil_vol_12_m_stb] [float],
    [val_acum_oil_vol_18_m_stb] [float],
    [val_acum_oil_vol_24_m_stb] [float],
    [val_acum_oil_vol_tot_tsb] [float],
    [val_acum_water_vol_1_m_bbl] [float],
    [val_acum_water_vol_3_m_bbl] [float],
    [val_acum_water_vol_6_m_bbl] [float],
    [val_acum_water_vol_12_m_bbl] [float],
    [val_acum_water_vol_18_m_bbl] [float],
    [val_acum_water_vol_24_m_bbl] [float],
    [val_acum_water_vol_tot_bbl] [float],
    [val_acum_cond_effective_vol_1_m_stb] [float],
    [val_acum_cond_effective_vol_3_m_stb] [float],
    [val_acum_cond_effective_vol_6_m_stb] [float],
    [val_acum_cond_effective_vol_12_m_stb] [float],
    [val_acum_cond_effective_vol_18_m_stb] [float],
    [val_acum_cond_effective_vol_24_m_stb] [float],
    [val_acum_cond_effective_vol_tot_stb] [float],
    [val_acum_gas_effective_vol_1_m_mscf] [float],
    [val_acum_gas_effective_vol_3_m_mscf] [float],
    [val_acum_gas_effective_vol_6_m_mscf] [float],
    [val_acum_gas_effective_vol_12_m_mscf] [float],
    [val_acum_gas_effective_vol_18_m_mscf] [float],
    [val_acum_gas_effective_vol_24_m_mscf] [float],
    [val_acum_gas_effective_vol_tot_mscf] [float],
    [val_acum_oil_effective_vol_1_m_stb] [float],
    [val_acum_oil_effective_vol_3_m_stb] [float],
    [val_acum_oil_effective_vol_6_m_stb] [float],
    [val_acum_oil_effective_vol_12_m_stb] [float],
    [val_acum_oil_effective_vol_18_m_stb] [float],
    [val_acum_oil_effective_vol_24_m_stb] [float],
    [val_acum_oil_effective_vol_tot_stb] [float],
    [val_acum_water_effective_vol_1_m_bbl] [float],
    [val_acum_water_effective_vol_3_m_bbl] [float],
    [val_acum_water_effective_vol_6_m_bbl] [float],
    [val_acum_water_effective_vol_12_m_bbl] [float],
    [val_acum_water_effective_vol_18_m_bbl] [float],
    [val_acum_water_effective_vol_24_m_bbl] [float],
    [val_acum_water_effective_vol_tot_bbl] [float],
    [val_total_stage_proppant] [float],
    [val_total_fluid_loading] [float],
    [val_gross_lateral_length] [float]
)
WITH
(
    DISTRIBUTION = HASH([cod_uwi]),
    CLUSTERED COLUMNSTORE INDEX
)
GO
