CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_well_header]
(
  [cod_uwi]                         NVARCHAR(4000)   NOT NULL,
  [des_common_name]                NVARCHAR(4000)   NULL,
  [des_well_name]                  NVARCHAR(4000)   NULL,
  [des_well_alias]                  NVARCHAR(4000)   NULL,
  [des_current_operator]           NVARCHAR(4000)   NULL,
  [des_country_name]               NVARCHAR(4000)   NULL,
  [des_state_or_province]         NVARCHAR(4000)   NULL,
  [des_county]                     NVARCHAR(4000)   NULL,
  [des_environment]               NVARCHAR(4000)   NULL,
  [id_basin]                       NVARCHAR(4000)   NULL,
  [des_short_name]                NVARCHAR(4000)   NULL,
  [des_existence_kind]            NVARCHAR(4000)   NULL,
  [fec_spud_date]                 DATETIME          NULL,
  [fec_abandoment_date]           DATETIME          NULL,
  [val_well_net_interest]         FLOAT             NULL,
  [des_well_net_interest_unit]   NVARCHAR(4000)   NULL,
  [val_water_depth]               FLOAT             NULL,
  [des_water_depth_unit]         NVARCHAR(4000)   NULL,
  [val_ground_elevation]         FLOAT             NULL,
  [des_ground_elevation_unit]    NVARCHAR(4000)   NULL,
  [des_slot_name]                NVARCHAR(4000)   NULL,
  [des_description]              NVARCHAR(4000)   NULL,
  [des_data_source]              NVARCHAR(4000)   NULL,
  [fec_create_date]              DATETIME          NULL,
  [des_create_user_id]           NVARCHAR(4000)   NULL,
  [fec_update_date]              DATETIME          NULL,
  [des_update_user_id]           NVARCHAR(4000)   NULL,
  [des_installation_name]        NVARCHAR(4000)   NULL,
  [des_installation_type]        NVARCHAR(4000)   NULL,
  [des_installation_identifier]  NVARCHAR(4000)   NULL,
  [des_gov_identifier]                    NVARCHAR(4000)   NULL,
  [des_proj_coord_unit]          NVARCHAR(4000)   NULL,
  [des_proj_coord_sys]           NVARCHAR(4000)   NULL,
  [val_easting]                  FLOAT             NULL,
  [val_northing]                 FLOAT             NULL,
  [des_geo_coord_sys]            NVARCHAR(4000)   NULL,
  [val_latitude]                 FLOAT             NULL,
  [val_longitude]                FLOAT             NULL,
  [des_well_ownership]           NVARCHAR(4000)   NULL,
  [des_well_business_unit]       NVARCHAR(4000)   NULL,
  [des_well_business_intention]  NVARCHAR(4000)   NULL,
  [des_well_category]            NVARCHAR(4000)   NULL,
  [des_posc_well_fluid_type]     NVARCHAR(4000)   NULL,
  [des_elevation_type]     NVARCHAR(4000)   NULL,
  [val_elevation]     FLOAT   NULL,
  [des_elevation_unit]     NVARCHAR(4000)   NULL,
  [des_elevation_datum]     NVARCHAR(4000)   NULL
)
WITH
(
  DISTRIBUTION = HASH(cod_uwi),
  CLUSTERED COLUMNSTORE INDEX
)
GO
