CREATE TABLE [sch_anl].[eyp0007_tb_fac_d_pwl_stat_prod]
(
  [fec_production_day] [smalldatetime] NOT NULL,
  [id_vers_well] [nvarchar] (4000) NOT NULL,
  [id_well] [nvarchar] (4000) NOT NULL,
  [id_commercial_entity] [nvarchar] (4000) NOT NULL,
  [id_facility_class_1] [nvarchar] (4000) NOT NULL,
  [id_well_hookup] [nvarchar] (4000) NOT NULL,
  [id_well_hole] [nvarchar] (4000) NOT NULL,
  [id_area] [nvarchar] (4000) NOT NULL,
  [id_productionunit] [nvarchar] (4000) NOT NULL,
  [id_geo_area] [nvarchar] (4000) NOT NULL,
  [id_field_cds] [nvarchar] (4000) NOT NULL,
  [id_field] [nvarchar] (4000) NOT NULL,
  [id_basin] [nvarchar] (4000) NOT NULL,
  [id_operator_route] [nvarchar] (4000) NOT NULL,
  [id_col_point] [nvarchar] (4000) NOT NULL,
  [id_licence] [nvarchar] (4000) NOT NULL,
  [ind_z_o_alloc_gl_vol_kscf] [float],
  [ind_alloc_cond_vol_stb] [float] ,
  [ind_alloc_cond_vol_sm3] [float] ,
  [ind_alloc_gas_vol_mscf] [float] ,
  [ind_alloc_gas_vol_kscf] [float] ,
  [ind_alloc_gas_vol_sm3] [float] ,
  [ind_alloc_gl_vol_kscf] [float],
  [ind_alloc_gl_vol_mscf] [float],
  [ind_alloc_gl_vol_sm3] [float],
  [ind_alloc_net_oil_vol_stb] [float] ,
  [ind_alloc_net_oil_vol_sm3] [float] ,
  [ind_alloc_water_vol_stb] [float] ,
  [ind_alloc_water_vol_sm3] [float] ,
  [ind_alloc_water_vol_bbl] [float] ,
  [ind_alloc_water_vol_m3] [float] ,
  [ind_o_alloc_cond_vol_15_sm3] [float],
  [ind_o_alloc_cond_vol_15_stb] [float],
  [ind_o_alloc_cond_vol_stb] [float] ,
  [ind_o_alloc_cond_vol_sm3] [float] ,
  [ind_o_alloc_gas_vol_15_kscf] [float],
  [ind_o_alloc_gas_vol_15_mscf] [float],
  [ind_o_alloc_gas_vol_15_sm3] [float],
  [ind_o_alloc_gas_vol_20_kscf] [float],
  [ind_o_alloc_gas_vol_20_mscf] [float],
  [ind_o_alloc_gas_vol_20_sm3] [float],
  [ind_o_alloc_gas_vol_mscf] [float] ,
  [ind_o_alloc_gas_vol_sm3] [float] ,
  [ind_o_alloc_gas_vol_kscf] [float] ,
  [ind_o_alloc_net_oil_vol_15_sm3] [float],
  [ind_o_alloc_net_oil_vol_15_stb] [float],
  [ind_o_alloc_net_oil_vol_20_sm3] [float],
  [ind_o_alloc_net_oil_vol_20_stb] [float],
  [ind_o_alloc_net_oil_vol_stb] [float] ,
  [ind_o_alloc_net_oil_vol_sm3] [float] ,
  [ind_o_alloc_water_vol_bbl] [float] ,
  [ind_o_alloc_water_vol_m3] [float] ,
  [ind_p_alloc_cond_vol_stb] [float] ,
  [ind_p_alloc_cond_vol_sm3] [float] ,
  [ind_p_alloc_gas_vol_15_kscf] [float],
  [ind_p_alloc_gas_vol_15_mscf] [float],
  [ind_p_alloc_gas_vol_15_sm3] [float],
  [ind_p_alloc_gas_vol_mscf] [float] ,
  [ind_p_alloc_gas_vol_sm3] [float] ,
  [ind_p_alloc_gas_vol_kscf] [float] ,
  [ind_p_alloc_net_oil_vol_15_sm3] [float],
  [ind_p_alloc_net_oil_vol_15_stb] [float],
  [ind_p_alloc_net_oil_vol_20_sm3] [float],
  [ind_p_alloc_net_oil_vol_20_stb] [float],
  [ind_p_alloc_net_oil_vol_stb] [float] ,
  [ind_p_alloc_net_oil_vol_sm3] [float] ,
  [ind_p_alloc_water_vol_bbl] [float] ,
  [ind_p_alloc_water_vol_m3] [float] ,
  [ind_theor_cond_rate_sm3] [float] ,
  [ind_theor_cond_rate_sm3perday] [float] ,
  [ind_theor_cond_rate_stb] [float] ,
  [ind_theor_cond_rate_stbperday] [float] ,
  [ind_theor_gas_rate_kscf] [float] ,
  [ind_theor_gas_rate_kscfperday] [float] ,
  [ind_theor_gas_rate_mscf] [float],
  [ind_theor_gas_rate_mscfperday] [float],
  [ind_theor_gas_rate_sm3] [float],
  [ind_theor_gas_rate_sm3perday] [float],
  [ind_theor_gl_rate_kscfperday] [float] ,
  [ind_theor_gl_rate_kscf] [float],
  [ind_theor_gl_rate_mscf] [float] ,
  [ind_theor_gl_rate_mscfperday] [float] ,
  [ind_theor_gl_rate_sm3] [float] ,
  [ind_theor_gl_rate_sm3perday] [float] ,
  [ind_theor_net_oil_rate_sm3] [float] ,
  [ind_theor_net_oil_rate_sm3perday] [float] ,
  [ind_theor_net_oil_rate_stb] [float] ,
  [ind_theor_net_oil_rate_stbperday] [float] ,
  [ind_theor_water_rate_bbl] [float] ,
  [ind_theor_water_rate_m3] [float] ,
  [ind_theor_water_rate_sm3perday] [float] ,
  [ind_theor_water_rate_stbperday] [float] ,
  [fec_create_date] [smalldatetime] ,
  [fec_update_date] [smalldatetime]
)
WITH
(
  DISTRIBUTION = HASH(id_well),
  CLUSTERED COLUMNSTORE INDEX
)
GO

