CREATE TABLE [sch_anl].[eyp0007_tb_dim_d_wellbore]
( 
  [id_vers]	[nvarchar] (4000) NOT NULL,
  [id_well_bore] [nvarchar] (4000)  NOT NULL,
  [des_well_bore] [nvarchar] (4000) ,
  [id_uwi] [nvarchar] (4000),
  [id_cds] [nvarchar] (4000),
  [des_wellbore_cds] [nvarchar] (4000),
  [fec_start_date] [smalldatetime] NOT NULL,
  [fec_end_date] [smalldatetime],
  [id_vers_well] [nvarchar] (4000) NOT NULL,
  [id_well] [nvarchar] (4000) ,
  [des_country] [nvarchar] (4000) ,
  [ind_east_utm_td] [float],
  [ind_north_utm_td] [float],
  [ind_rkb_depth] [float],
  [ind_sidetrack_depth] [float],
  [ind_tvdss_depth] [float],
  [ind_borehole_number] [float],
  [des_common_name] [nvarchar] (4000),
  [des_current_purpose] [nvarchar] (4000),
  [fec_completed_date] [smalldatetime],
  [des_depth_ref_datum] [nvarchar] (4000),
  [ind_depth_ref_elev] [float],
  [des_depth_ref_elev_unit] [nvarchar] (4000),
  [des_depth_ref_point] [nvarchar] (4000),
  [des_drilling_operator] [nvarchar] (4000),
  [des_drilling_permit] [nvarchar] (4000),
  [id_field] [nvarchar] (4000),
  [des_field] [nvarchar] (4000),
  [ind_ground_elev] [float],
  [des_ground_elev_unit] [nvarchar] (4000),
  [des_innitial_purpose] [nvarchar] (4000),
  [ind_kickoff_depth] [float],
  [des_kickoff_depth_unit] [nvarchar] (4000),
  [des_kind] [nvarchar] (4000),
  [des_norm_bh_geo_coord_sys] [nvarchar] (4000),
  [ind_normalized_bh_latitude] [float],
  [ind_normalized_bh_longitude] [float],
  [des_original_operator] [nvarchar] (4000),
  [id_cds_parent] [nvarchar] (4000),
  [des_pref_bh_geo_coord_sys] [nvarchar] (4000),
  [ind_preferred_bh_latitude] [float],
  [ind_preferred_bh_longitude] [float],
  [des_pref_bh_prj_coord_sys] [nvarchar] (4000),
  [des_pref_bh_prj_coord_unit] [nvarchar] (4000),
  [ind_preffered_bh_easting] [float],
  [ind_preffered_bh_northing] [float],
  [fec_spud_date] [datetime2], 
  [ind_total_depth_final] [float],
  [des_total_depth_final_unit] [nvarchar] (4000),
  [ind_total_depth_planned] [float],
  [des_total_depth_planned_unit] [nvarchar] (4000),
  [des_trajectory_shape] [nvarchar] (4000),
  [fec_create_date] [smalldatetime],
  [fec_update_date] [smalldatetime]
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX (id_vers)
)
GO
