CREATE TABLE [sch_anl].[eyp0007_tb_fac_m_str_plan_targ]
(
  [fec_production_day] [smalldatetime] NOT NULL,
  [id_vers_stream] [nvarchar] (4000) NOT NULL,
  [id_stream] [nvarchar] (4000) NOT NULL,
  [id_fcty_class_1] [nvarchar] (4000) NOT NULL,
  [id_col_point] [nvarchar] (4000) NOT NULL,
  [id_productionunit] [nvarchar] (4000) NOT NULL,
  [id_area] [nvarchar] (4000) NOT NULL,
  [id_operator_route] [nvarchar] (4000) NOT NULL,
  [id_product] [nvarchar] (4000) NOT NULL,
  [id_licence] [nvarchar] (4000) NOT NULL,
  [id_disposition_type] [nvarchar] (4000) NOT NULL,
  [des_comments] [nvarchar] (4000),
  [ind_cond_upa1_kstbpermth] [float],
  [ind_cond_upa1_stbpermth] [float],
  [ind_cond_upa2_kstbpermth] [float],
  [ind_cond_upa2_stbpermth] [float],
  [ind_cond_upa3_kstbpermth] [float],
  [ind_cond_upa3_stbpermth] [float],
  [ind_cond_upa4_kstbpermth] [float],
  [ind_cond_upa4_stbpermth] [float],
  [ind_cond_upa5_kstbpermth] [float],
  [ind_cond_upa5_stbpermth] [float],
  [ind_cond_upa6_kstbpermth] [float],
  [ind_cond_upa6_stbpermth] [float],
  [ind_cond_upa7_kstbpermth] [float],
  [ind_cond_upa7_stbpermth] [float],
  [ind_cond_upa8_kstbpermth] [float],
  [ind_cond_upa8_stbpermth] [float],
  [ind_cond_upa9_kstbpermth] [float],
  [ind_cond_upa9_stbpermth] [float],
  [ind_cond_upa10_kstbpermth] [float],
  [ind_cond_upa10_stbpermth] [float],
  [ind_cond_upa11_kstbpermth] [float],
  [ind_cond_upa11_stbpermth] [float],
  [ind_cond_upa12_kstbpermth] [float],
  [ind_cond_upa12_stbpermth] [float],
  [ind_gas_upa1_mmscfpermth] [float],
  [ind_gas_upa1_kscfpermth] [float],
  [ind_gas_upa2_mmscfpermth] [float],
  [ind_gas_upa2_kscfpermth] [float],
  [ind_gas_upa3_mmscfpermth] [float],
  [ind_gas_upa3_kscfpermth] [float],
  [ind_gas_upa4_mmscfpermth] [float],
  [ind_gas_upa4_kscfpermth] [float],
  [ind_gas_upa5_mmscfpermth] [float],
  [ind_gas_upa5_kscfpermth] [float],
  [ind_gas_upa6_mmscfpermth] [float],
  [ind_gas_upa6_kscfpermth] [float],
  [ind_gas_upa7_mmscfpermth] [float],
  [ind_gas_upa7_kscfpermth] [float],
  [ind_gas_upa8_mmscfpermth] [float],
  [ind_gas_upa8_kscfpermth] [float],
  [ind_gas_upa9_mmscfpermth] [float],
  [ind_gas_upa9_kscfpermth] [float],
  [ind_gas_upa10_mmscfpermth] [float],
  [ind_gas_upa10_kscfpermth] [float],
  [ind_gas_upa11_mmscfpermth] [float],
  [ind_gas_upa11_kscfpermth] [float],
  [ind_gas_upa12_mmscfpermth] [float],
  [ind_gas_upa12_kscfpermth] [float],
  [ind_ngl_upa1_kstbpermth] [float],
  [ind_ngl_upa1_stbpermth] [float],
  [ind_ngl_upa2_kstbpermth] [float],
  [ind_ngl_upa2_stbpermth] [float],
  [ind_ngl_upa3_kstbpermth] [float],
  [ind_ngl_upa3_stbpermth] [float],
  [ind_ngl_upa4_kstbpermth] [float],
  [ind_ngl_upa4_stbpermth] [float],
  [ind_ngl_upa5_kstbpermth] [float],
  [ind_ngl_upa5_stbpermth] [float],
  [ind_ngl_upa6_kstbpermth] [float],
  [ind_ngl_upa6_stbpermth] [float],
  [ind_ngl_upa7_kstbpermth] [float],
  [ind_ngl_upa7_stbpermth] [float],
  [ind_ngl_upa8_kstbpermth] [float],
  [ind_ngl_upa8_stbpermth] [float],
  [ind_ngl_upa9_kstbpermth] [float],
  [ind_ngl_upa9_stbpermth] [float],
  [ind_ngl_upa10_kstbpermth] [float],
  [ind_ngl_upa10_stbpermth] [float],
  [ind_ngl_upa11_kstbpermth] [float],
  [ind_ngl_upa11_stbpermth] [float],
  [ind_ngl_upa12_kstbpermth] [float],
  [ind_ngl_upa12_stbpermth] [float],
  [ind_oil_upa1_kstbpermth] [float],
  [ind_oil_upa1_stbpermth] [float],
  [ind_oil_upa2_kstbpermth] [float],
  [ind_oil_upa2_stbpermth] [float],
  [ind_oil_upa3_kstbpermth] [float],
  [ind_oil_upa3_stbpermth] [float],
  [ind_oil_upa4_kstbpermth] [float],
  [ind_oil_upa4_stbpermth] [float],
  [ind_oil_upa5_kstbpermth] [float],
  [ind_oil_upa5_stbpermth] [float],
  [ind_oil_upa6_kstbpermth] [float],
  [ind_oil_upa6_stbpermth] [float],
  [ind_oil_upa7_kstbpermth] [float],
  [ind_oil_upa7_stbpermth] [float],
  [ind_oil_upa8_kstbpermth] [float],
  [ind_oil_upa8_stbpermth] [float],
  [ind_oil_upa9_kstbpermth] [float],
  [ind_oil_upa9_stbpermth] [float],
  [ind_oil_upa10_kstbpermth] [float],
  [ind_oil_upa10_stbpermth] [float],
  [ind_oil_upa11_kstbpermth] [float],
  [ind_oil_upa11_stbpermth] [float],
  [ind_oil_upa12_kstbpermth] [float],
  [ind_oil_upa12_stbpermth] [float],
  [fec_create_date] [smalldatetime],
  [fec_update_date] [smalldatetime]
)
WITH
(
	DISTRIBUTION = HASH(id_stream),
	CLUSTERED COLUMNSTORE INDEX
)
GO